### ISSUE TITLE
Toolbar placement

### ISSUE THREAD

**Issue by logzero** [AlienCowEatCake/ImageViewer#10]
The toolbar on Windows is at the bottom. Is it possible to have it at the top (below menu bar)? I guess bars being toggleable complicates it somewhat?

**Comment by AlienCowEatCake** [comment]
ComboBox "Toolbar Position" was added to Preferences dialog:
![Screenshot 2023-10-23 144400](https://github.com/AlienCowEatCake/ImageViewer/assets/1363547/f65f9336-a7f4-40db-bc86-b7968baa05e0)

This feature will be available in next release

**Comment by AlienCowEatCake** [comment]
Released in [v1.5.4](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.5.4)
