### ISSUE TITLE
Fit a smaller image to window size

### ISSUE THREAD

**Issue by logzero** [AlienCowEatCake/ImageViewer#11]
It would be nice if there was an option to auto zoom in (scale up, grow) the image to fit the view.

**Comment by AlienCowEatCake** [comment]
Option "Allow fit to window for small images" was added to Preferences dialog:
![Screenshot 2023-10-23 144548](https://github.com/AlienCowEatCake/ImageViewer/assets/1363547/7d698612-abb0-49d9-a43d-0ba68f05f7cc)

This feature will be available on next release

**Comment by AlienCowEatCake** [comment]
Released in [v1.5.4](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.5.4)
