### ISSUE TITLE
Close Hotkey

### ISSUE THREAD

**Issue by sterno900** [AlienCowEatCake/ImageViewer#14]
can we get either ESC or CTRL+W  to close the window ? (on windows)

**Comment by AlienCowEatCake** [comment]
Hotkey Ctrl+W was added as exit alias (closes main window). For dialog windows Esc should already work as close hotkey.
This will be available in next release

**Comment by AlienCowEatCake** [comment]
Released in [v1.6.2](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.6.2)
