### ISSUE TITLE
Option to use system icons on Linux?

### ISSUE THREAD

**Issue by butyoutried** [AlienCowEatCake/ImageViewer#18]
Продолжу на русском: это здорово поможет адаптировать просмотрщик к общему окружению. У меня, например, с несменяемыми монохромными значками он заметно выбивается из стиля.

**Comment by AlienCowEatCake** [comment]
Опция выбора системных иконок добавлена в диалог настроек. Будет доступно в следующем релизе

**Comment by butyoutried** [comment]
Спасибо! Собрал, стало лучше.

**Comment by AlienCowEatCake** [comment]
Выпущено в [релизе 1.7.0](https://github.com/AlienCowEatCake/ImageViewer/releases/tag/v1.7.0)
